from funciones_personalizadas.graficos import discretizacion_en_malla_rectangular, graficar_isobaras_presion, graficar_isobaras_presion_y_campo_velocidad
from funciones_personalizadas.tablas import generar_matriz
from funciones_personalizadas.solver import algoritmo_thomas_2D